### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by philipstanislaus** [Joystream/parity-codec-go#6]
Dear Joystream team, 

Thanks for your work on this implementation! 

We are currently building a [Substrate RPC client in Go](https://github.com/centrifuge/go-substrate-rpc-client), and are using your codec. Since we require additional features, we'd love to contribute to your repository. 

I see very little activity in this repository – what are your long term plans for maintenance and development of this library? 

How can we best work together? 

Best 

Philip

**Comment by philipstanislaus** [comment]
@mnaamani can I get in touch with your team regarding this issue? 

Thanks!

**Comment by mnaamani** [comment]
Hi @philipstanislaus 
We are very happy to see that you found the library useful. Currently we have no near term plans to invest more in developing the library, since we are working directly with the rust implementation.

We welcome collaboration, and would be happy to to accept PRs. Althouhgh we don't have anyone full-time dedicated to maintain the repo we will do our best to review and merge.

Long term we still hope this codec implementation will be part of other projects supporting writing smart contracts for substrate in `Go`.
